version: '3.4'

services:
  coinwallet.web:
    image: ${DOCKER_REGISTRY-}coinwalletweb
    build:
      context: .
      dockerfile: CoinWallet/Dockerfile
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "MyPassword001"
        ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"